### ISSUE TITLE
lakers-c: error parsing message 2 (in some platforms)

### ISSUE THREAD

**Issue by geonnave** [openwsn-berkeley/lakers#234]
When integrating the latest version of `lakers-c` in the DotBot, `initiator_parse_message_2` always fails with `ParsingError`.
This behavior was also observed my a native target, although only happening intermittently.
I think the same issue was found when @malishav used `lakers-c` with the `AIOT Play` platform, although in that case initializing all to zero solved the issue.

Specifically, the error happens in `decode_plaintext_2`, where the `plaintext_2` parameter seems to be overwritten by seemingly random bytes.

I suspect of an issue with pointers in the FFI boundary, but so far I could not isolate the exact source.

The plan of action is to research and implement guidelines for safer Rust-to-C FFIs, and re-test.

**Comment by chrysn** [comment]
Are any of the tests running with ASAN or similar tools?

**Comment by geonnave** [comment]
ASAN is new to me, I am using it to investigate, thank you for the pointer.

**Comment by chrysn** [comment]
![asan](https://github.com/openwsn-berkeley/lakers/assets/442326/27f086c3-938a-4b32-a1a5-544bb3f1ac10)

**Comment by chrysn** [comment]
It may also be UBSAN, they're best used both together.

**Comment by geonnave** [comment]
In the end, the bug was not in the FFI. Actual source is #242, and it was fixed by #243.
