### ISSUE TITLE
Release 0.6.1?

### ISSUE THREAD

**Issue by chrysn** [openwsn-berkeley/lakers#285]
With #281, I think we should have interoperable credential-by-value, but it's a bit hard to test without bending all the versions to match.

@geonnave, could we have a release v0.6.1 along with an updated Python release based on what we have, roughly, now, before the big changes of #284 and #274 start hitting main?

**Comment by geonnave** [comment]
Yes, I can do that.

**Comment by chrysn** [comment]
For the benefit of others who do not read our chat messages: that change was https://github.com/openwsn-berkeley/lakers/pull/286 and is merged now.
