### ISSUE TITLE
Remaining interoperability issue

### ISSUE THREAD

**Issue by chrysn** [openwsn-berkeley/lakers#301]
In tests with Marco's Java version, the 0.3.3 Python version has not achieved interoperability yet when sending the credential by value (failing MAC verification).

We'll continue testing once everyone is back at work.

**Comment by chrysn** [comment]
The issue fixed in #284 (https://github.com/openwsn-berkeley/lakers/issues/303#issuecomment-2453233409) could well have been the remaining issue; we'll see tomorrow when plugtesting with the coap://demo.coap.amsuess.com server.

**Comment by geonnave** [comment]
Cool!

**Comment by geonnave** [comment]
I think this is fixed now?

**Comment by chrysn** [comment]
Yes, #284 fixed this.
